spring:
    datasource:
        password: admin
        url: jdbc:postgresql://localhost:5432/hrms
        username: admin
    jpa:
        hibernate:
            ddl-auto: update
            

                         
resilience4j.timelimiter:    instances:     
     PRODUCTSERVICE:
        timeout-duration: 2s
        cancel-running-future: true
resilience4j.retry:
    instances:
      PRODUCTSERVICE:
        max-attempts: 4
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        exponential-max-wait-duration: 500ms          
        #ignore-exceptions:         # - java.util.concurrent.TimeoutException
        retry-exceptions:          - java.net.SocketException
          - java.net.ConnectException
          - java.util.concurrent.TimeoutException
          - java.lang.RuntimeException

        
        
          

logging:  level:    '[io.github.resilience4j.timelimiter,io.github.resilience4j.retry]': DEBUG
debug: false
      


          
       
      

 